# This is dockerfile script for testing install scripts

# Defining mandatory variables
ARG DISTRO
ARG DISTRO_VERSION
ARG PACKAGE_MANAGER

# Defining optional variables
ARG DOCKER_IMAGE
ARG SCRIPT

# If not set, set default values
ARG APP_IMAGE=${DOCKER_IMAGE:-${DISTRO}:${DISTRO_VERSION}}
ARG SCRIPT_TARGET=${SCRIPT:-rae-${DISTRO}-install.sh}

# hadolint ignore=DL3006
FROM ${APP_IMAGE} as base
ENV DEBIAN_FRONTEND=noninteractive
ENV LANGUAGE=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LC_CTYPE=en_US.UTF-8

FROM base as apt-manager
# hadolint ignore=DL3008
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    sudo \
    locales \
    procps \
    && \
    rm -rf /var/lib/apt/lists/* && \
    echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen --purge 'en_US.UTF-8'

FROM base as pacman-manager
RUN pacman -Syu --noconfirm --needed \
    sudo \
    && \
    rm -rf /var/lib/pacman/sync/*

# hadolint ignore=DL3006
FROM ${PACKAGE_MANAGER}-manager as final
RUN useradd test --create-home --shell /bin/bash && \
    echo "test ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
WORKDIR /home/test
ARG SCRIPT_TARGET
COPY ${SCRIPT_TARGET} test-install-script.sh
RUN chown test:test test-install-script.sh && \
    chmod +x test-install-script.sh
USER test
ENTRYPOINT ["sudo","--set-home", "--preserve-env", "./test-install-script.sh", "--all"]
