name: ⭕️ Ubuntu script install - tests

on:
  pull_request:
    paths:
      - scripts/rae-ubuntu-install.sh
      - scripts/dockerfile
    branches: [main]
  push:
    paths:
      - scripts/rae-ubuntu-install.sh
      - scripts/dockerfile
    branches: [main]
  schedule:
    - cron: 0 0 1 * *

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-ubuntu-bionic:
    name: ⭕️ Test Ubuntu bionic
    uses: ./.github/workflows/01-reusable-test-install-scripts.yml
    with:
      distro: ubuntu
      distro-version: bionic
      package-manager: apt
      script: rae-ubuntu-install.sh

  test-ubuntu-focal:
    name: ⭕️ Test Ubuntu focal
    uses: ./.github/workflows/01-reusable-test-install-scripts.yml
    with:
      distro: ubuntu
      distro-version: focal
      package-manager: apt
      script: rae-ubuntu-install.sh

  test-ubuntu-jammy:
    name: ⭕️ Test Ubuntu jammy
    uses: ./.github/workflows/01-reusable-test-install-scripts.yml
    with:
      distro: ubuntu
      distro-version: jammy
      package-manager: apt
      script: rae-ubuntu-install.sh
