name: Ubuntu script install - tests

on:
  pull_request:
    paths: [scripts/rae-ubuntu-install.sh]
    branches: [main]
  push:
    paths: [scripts/rae-ubuntu-install.sh]
    branches: [main]
  schedule:
    - cron: 0 0 1 * *
jobs:
  test-ubuntu-bionic:
    uses: ./.github/workflows/01-reusable-test-install-scripts.yml
    with:
      distro: ubuntu
      distro-version: bionic
      package-manager: apt
      script: rae-ubuntu-install.sh

  test-ubuntu-focal:
    uses: ./.github/workflows/01-reusable-test-install-scripts.yml
    with:
      distro: ubuntu
      distro-version: focal
      package-manager: apt
      script: rae-ubuntu-install.sh
