name: 🔖 Pull Request Labeler

on:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    name: 🔖 Pull Request Labeler
    runs-on: ubuntu-20.04
    steps:
      - name: 🚀 Run labeler
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
          configuration-path: .github/labels/labeler.yml
