name: Docker image ci

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  avoid_redundancy:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel redundant workflow
        uses: styfle/cancel-workflow-action@0.9.1
  build:
    runs-on: ubuntu-20.04
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build Docker image and export
        uses: docker/build-push-action@v3
        with:
          context: docker
          tags: ${{github.repository}}:${{github.sha}}
          outputs: type=docker,dest=/tmp/docker-image-${{ github.sha }}.tar.gz
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image-${{ github.sha }}.tar.gz
          path: /tmp/docker-image-${{ github.sha }}.tar.gz

  publish:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image-${{ github.sha }}.tar.gz
          path: /tmp/docker-image-${{ github.sha }}.tar.gz
      -
        name: Load image
        run: |
          docker load -i /tmp/docker-image-${{ github.sha }}.tar.gz
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Publish image
        run: |
          docker push ${{ github.repository }}:${{ github.sha }}
