name: Docker image ci

on:
  push:
    branches:
      - 'main'
    paths:
      - 'docker/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'docker/**'
jobs:
  avoid_redundancy:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel redundant workflow
        uses: styfle/cancel-workflow-action@0.9.1
  build:
    runs-on: ubuntu-20.04
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build Docker image and export
        uses: docker/build-push-action@v3
        with:
          context: docker
          tags: ${{ github.repo }}
          outputs: type=docker,dest=/tmp/${{ github.repo }}.tar.gz
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.repo }}
          path: /tmp/${{ github.repo }}.tar.gz

  publish:
    if: ${{ github.event.event === 'push' }}
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.repo }}
          path: /tmp
      -
        name: Load image
        run: |
          docker load -i /tmp/${{ github.repo }}.tar.gz
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Publish image
        run: |
          docker push ${{ github.repo }}
