name: Docker image ci

on:
  push:
    paths: [docker/**]
    branches: [main]
  pull_request:
    paths: [docker/**]
    branches: [main]
jobs:
  avoid_redundancy:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel redundant workflow
        uses: styfle/cancel-workflow-action@0.9.1
  build:
    runs-on: ubuntu-20.04
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build Docker image and export
        uses: docker/build-push-action@v3
        with:
          context: docker
          tags: ${{ secrets.DOCKERHUB_REPO }}:${{ github.run_number }}, ${{ secrets.DOCKERHUB_REPO }}:latest
          outputs: type=docker,dest=/tmp/docker-image-${{ github.run_number }}.tar.gz
      -
        if: ${{ github.event_name == 'push' }}
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image-${{ github.run_number }}.tar.gz
          path: /tmp/docker-image-${{ github.run_number }}.tar.gz

  publish:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: docker-image-${{ github.run_number }}.tar.gz
          path: /tmp/
      -
        name: Load image
        run: |
          docker load -i /tmp/docker-image-${{ github.run_number }}.tar.gz
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      -
        name: Publish image
        run: |
          docker push ${{ secrets.DOCKERHUB_REPO }}:${{ github.run_number }}
          docker push ${{ secrets.DOCKERHUB_REPO }}:latest
