name: Ubuntu script install - tests
on:
  pull_request:
    paths: [scripts/rae-ubuntu-install.sh]
    branches: [main]
jobs:
  test-ubuntu-focal:
    runs-on: ubuntu-20.04
    steps:
      -
        uses: actions/checkout@v2
      -
        name: install sudo
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y sudo
      -
        name: execute install script
        run: |
          chmod +x ./scripts/rae-ubuntu-install.sh
          sudo -E ./scripts/rae-ubuntu-install.sh -a
  test-ubuntu-bionic:
      runs-on: ubuntu-18.04
      steps:
        -
          uses: actions/checkout@v2
        -
          name: install locales
          run: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update
            apt-get install -y locales
            locale-gen en_US.UTF-8
            dpkg-reconfigure -f noninteractive locales
            export LANG=en_US.UTF-8
            export LC_ALL=en_US.UTF-8
            export LANGUAGE=en_US.UTF-8
        -
          name: install sudo
          run: |
            apt-get install -y sudo
        -
          name: execute install script
          run: |
            chmod +x ./scripts/rae-ubuntu-install.sh
            sudo -E ./scripts/rae-ubuntu-install.sh -a