name: Debian script install - tests

on:
  pull_request:
    paths: [scripts/rae-debian-install.sh]
    branches: [main]
jobs:
  shell-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: azohra/shell-linter@latest
        with:
          path: scripts/rae-debian-install.sh

  test-debian-10:
    needs: [shell-check]
    uses: ./test-install-scripts.yml
    with:
      distro: debian
      distro-version: 10
      package-manager: apt
      script: rae-debian-install.sh

  test-debian-11:
    needs: [shell-check]
    uses: ./test-install-scripts.yml
    with:
      distro: debian
      distro-version: 11
      package-manager: apt
      script: rae-debian-install.sh
