name: Ubuntu script install - tests

on:
  pull_request:
    paths: [scripts/rae-ubuntu-install.sh]
    branches: [main]
jobs:
  shell-check:
    runs-on: ubuntu-20.04
    steps:
      - 
        uses: actions/checkout@v3
      -
        name: Run ShellCheck
        uses: azohra/shell-linter@0.9.1
        with:
          path: scripts/rae-ubuntu-install.sh
  ubuntu-focal:
    needs: [shell-check]  
    runs-on: ubuntu-20.04
    steps:
      -
        uses: actions/checkout@v3
      -
        name: execute install script
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo chmod +x ./scripts/rae-ubuntu-install.sh
          sudo -E ./scripts/rae-ubuntu-install.sh -a
  ubuntu-bionic:
      needs: [shell-check]  
      runs-on: ubuntu-18.04
      steps:
        -
          uses: actions/checkout@v3
        -
          name: execute install script
          run: |
            export DEBIAN_FRONTEND=noninteractive
            sudo chmod +x ./scripts/rae-ubuntu-install.sh
            sudo -E ./scripts/rae-ubuntu-install.sh -a